task_id:"-b7DPrRCV-0CMQAyuF6oQ" situation_id:"imjv56ThY25lTi40ca41W" check_item:{check_item_id:"_-tEPm94ChBjZqk4AvUsY" command:{command_id:"QRLFFpKbwmDXwS02gWa36" command_line:"progate diagnose"} command:{command_id:"BzD6pfIcDxrHe_ExlNv75" command_line:"bash ./.progate/check_puppeteer.sh"}} check_item:{check_item_id:"QZDqYy8p6Q6eNScVBMwgF" command:{command_id:"ZY0khrKDVM1LmmrU4DeMF" command_line:"npm run test"}}